#!/usr/bin/env bash

clear;
parameters=("$@")

if [[ ${#} < 1 ]]; then
  echo "---------------------------------------------------------------------------------------------------------------"
  echo "Manual (But Still Lazy) CloudFormation Template Build & Deploy"
  echo "---------------------------------------------------------------------------------------------------------------"
  echo
  echo "IMPORTANT NOTE: Because I am lazy it is expected that this script is run from a folder containing one or more"
  echo "                project folder. If you're feeling energetic you can refudge my bash and make this more flexible"
  echo
  echo "Usage:"
  echo
  echo "  build-all [PROJECT] [ENVIRONMENT...1] [ENVIRONMENT...n]";
  echo
  echo "Parameters:"
  echo
  echo "  PROJECT           Name of the project folder to be build (use asterisk in quotes \"*\" to build all projects)"
  echo "  ENVIRONMENT...x   Name of the environment (or environments) to be build. Omit this parameter to build all environments"
  echo
  echo "Examples:"
  echo
  echo "  build-all Manage Dev Uat      Build 'Manage' project in the 'Dev' and 'Uat' environments only"
  echo "  build-all Manage              Build 'Manage' project in all environments"
  echo "  build-all \"*\"               Build all projects and all environments"
  echo
fi

echo "---------------------------------------------------------------------------------------------------------------"
echo "Manual (But Still Lazy) CloudFormation Template Build & Deploy (Patent Pending)"
echo "---------------------------------------------------------------------------------------------------------------"

# Convert parameter to lowercase
to_lower() {
  python -c "print('${1}'.lower())";
}

# Convert parameter to UPPERCASE
to_upper() {
  python -c "print('${1}'.upper())";
}

# Convert parameter to TitleCase
to_title() {
  python -c "print('${1}'.lower().title())";
}

timestamp=$(date +%s%3N)

regions=(UsEast1 ApSoutheast2)

if [[ "${parameters[0]}" == "*" ]]; then
  projects=()
  for directory in ./*; do
    projects+=("$(basename ${directory})")
  done
else
  projects=(${parameters[0]} )
fi

if [[ ${#} > 1 ]]; then
  environments=()
  for i in $(seq 2 $((${#})) ); do
    environments+=("${parameters[$i-1]}")
  done
fi

artifact_id_snake=$(echo ${artifact_id} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');

for project in "${projects[@]}"; do
  if [[ "${parameters[0]}" == "${project}" || "${parameters[0]}" == "*" ]]; then
    if [[ ! -d ./${project} ]]; then
      echo "ERROR: Could not locate project folder, please ensure you are running this in the correct folder"
      exit 1;
    fi

    if [[ -d ../Output/${project} ]]; then
      mkdir -p ../Backups/${project}/${timestamp}
      mv ../Output/${project} ../Backups/${timestamp}
    fi

    for region_current in "${regions[@]}"; do
      region_current_hyphen=$(echo ${region_current} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');
      region_current_hyphen=$(to_lower ${region_current_hyphen})

      for region_folder in ./${project}/*; do
        if [[ -d ${region_folder} ]]; then
          region_folder=$(basename ${region_folder})
          region_hyphen=$(echo ${region_folder} | sed 's/\([a-z0-9]\)\([A-Z0-9]\)/\1-\L\2/g');
          region_hyphen=$(to_lower ${region_hyphen})

          if [[ "${region_current_hyphen}" == "${region_hyphen}" ]]; then
            for environment in ./${project}/${region_folder}/*; do
              if [[ -d ${environment} ]]; then
                environment=$(basename ${environment})
                if [[ ${#} < 2 || "${environments[@]}" =~ "${environment}" ]]; then
                  environment_lower=$(to_lower ${environment})
                  project_lower=$(to_lower ${project})
                  aws_account_id=$(cat ./${project}/${region_folder}/BuildManifest.json | jq -r ".Infrastructure.Environments[\"${environment}\"].AwsAccountId")
                  s3_bucket="artifacts.infrastructure-manual.${project_lower}.${environment_lower}.eonx.com"
                  s3_prefix="Infrastructure/${timestamp}"

                  echo
                  echo "Project:                ${project_lower}"
                  echo "Environment:            ${environment_lower}"
                  echo "AWS Account:            ${aws_account_id}"
                  echo "AWS Region:             ${region_hyphen}"
                  echo "Template Bucket:        ${s3_bucket}/${s3_prefix}"
                  echo

                  builder \
                    --config      ./${project}/${region_folder}/BuildManifest.json \
                    --path-output ../Output/${project}/${region_folder} \
                    --environment ${environment}
                  echo
                  echo "---------------------------------------------------------------------------------------------------------------"
                fi
              fi
            done
          fi
        fi
      done
    done

  fi
done

echo




